import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { CustomCartProvider } from "@/lib/context/CustomCartProvider";
// import { HeroUIProvider } from "@heroui/react";

// Import Lexend with the correct settings
const lexend = Lexend({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap", // Improves font rendering
  variable: "--font-lexend", // This is important for Tailwind
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lexend.variable}>
      <body className="antialiased">
        {/* <HeroUIProvider> */}
          <CustomCartProvider>
            <Header />
            {children}
            <Footer />
          </CustomCartProvider>
        {/* </HeroUIProvider> */}
      </body>
    </html>
  );
}
